import "./globals.css";
import { JetBrains_Mono } from "next/font/google";

import Header from "@/components/Header/Header";

// Подключение шрифта JetBrains Mono
const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: '--font-jetbrainsMono', // Глобальная CSS-переменная для шрифта
});

// Мета-информация для страниц
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        type: "image/svg+xml",
        url: "/favicon.svg"
      },
    ],
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <body className={jetbrainsMono.variable}>
        <Header />
        {children}
      </body>
    </html>
  );
}